server:
  port: 8761

spring:
  application:
    name: discovery-service



security:
  basic:
    enabled: true
  user:
      name: discoveryUser # login username
      password: passwordDiscovery
#  cloud:
#    config:
#        name: discovery
#        uri: =http://localhost:8881
#        username:   configUser
#        password: configPassword

#eureka.server.e